RESOLUTION_X: int = 1280
RESOLUTION_Y: int = 720

BUG_SCREAM_RADIUS: int = 90
BUG_MAX_SPEED: int = 35
BUG_MIN_SPEED: int = 15
BUG_NOSE_LENGTH: int = 10
BUG_SIZE: int = 3

BUG_COUNT: int = 200
CHUNK_UPDATE_AFTER_TICKS:int = 10
